
#ifndef __FRONTEND_PROMPTS_HGM_H__
#define __FRONTEND_PROMPTS_HGM_H__
// -- GENERATED BY MAYA

const int BG_MESSAGE = 0;
const int BTN_NO = 1;
const int BTN_YES = 2;

#endif // __FRONTEND_PROMPTS_HGM_H__
