
#ifndef __GAMEOVER_ARCADE_HGM_H__
#define __GAMEOVER_ARCADE_HGM_H__
// -- GENERATED BY MAYA

const int GFX_GAMEOVER_TITLE = 0;
const int BTN_QUIT = 1;
const int BTN_TRYAGAIN = 2;

#endif // __GAMEOVER_ARCADE_HGM_H__
