

#ifndef __TIMEUP_HUI_H__
#define __TIMEUP_HUI_H__

// -- GENERATED BY MAYA

const int HUI_BUTTON_CONTINUE = 1000;
const int HUI_GFX_DIM = 1001;
const int HUI_GLYPH_NEXT = 1002;

#endif // __TIMEUP_HUI_H__
