
/*===================================================================
	File: CabbyAccess.h
	Game: Cabby

	(C)Hidden Games
=====================================================================*/

#ifndef __CABBYACCESS_H__
#define __CABBYACCESS_H__

#include "ScriptBase.h"

// forward declare
class ScriptDataHolder;

struct GameData
{
	int MAX_ITEMS_PER_PACK;
	int TOTAL_LEVELS;
	int TOTAL_VEHICLES;
	int TOTAL_LEVEL_PACKS;
	int TOTAL_VEHICLE_PACKS;

	float ACHIEVEMENT_ICON_MAXX;
	float ACHIEVEMENT_ICON_SPEED;
	float ACHIEVEMENT_ICON_SHOWTIME;

#ifdef CABBY_FREE
	float ADBAR_PHONE_POSX;
	float ADBAR_PHONE_POSY;	
	float ADBAR_TABLET_POSX;
	float ADBAR_TABLET_POSY;
#endif // CABBY_FREE

	// ui
	float SPEECHBUBBLE_XOFFSET_PHONE_SD;
	float SPEECHBUBBLE_YOFFSET_PHONE_SD;
	float SPEECHBUBBLE_XOFFSET_PHONE_RETINA;
	float SPEECHBUBBLE_YOFFSET_PHONE_RETINA;
	float SPEECHBUBBLE_XOFFSET_TABLET_SD;
	float SPEECHBUBBLE_YOFFSET_TABLET_SD;

	float ICON_LOWEST_POS;
	float ICON_HIGHEST_POS;
	float ICON_EDGE_CLOSEST;

	float FUEL_BAR_WIDTH;
	float FUEL_BAR_HEIGHT;	

	float TOWTRUCK_FLYBY_SPEED;

	int MAX_PLAYLISTNAME_CHARACTERS;
	int MAX_SONGNAME_CHARACTERS;

	// sprites
	int NIGHT_SPRITES_START;

	// game
	float ARCADE_TIME;
	int ARCADE_CUSTOMERS;
	int ARCADE_FUEL;
	int ARCADE_MONEY;
	float ARCADE_STAR_ROTATION;
	float ARCADE_STAR_COLLISION_RADIUS;

	int FARE_LOW;
	int FARE_MEDIUM;
	int FARE_HIGH;
	int FARE_COURIER;
	int FARE_PERFECT;
	int FARE_MINIMUM;

	int WAIT_DECREASE_SECS;
	int WAIT_FARE_LOSS;

	int TRAVEL_DECREASE_SECS;
	int TRAVEL_FARE_LOSS;

	int ROUGHLANDING_FARE_LOSS;

	int PASSENGER_LOSS;
	int PARCEL_LOSS;

	int FUEL_CHARGE;
	int TOW_TRUCK_CHARGE;

	int NEW_LIFE_AWARD;
	int CONTINUE_COST;

	int DELIVERY_VAN_UNLOCK_TOTALPARCELS;
	int HOTROD_UNLOCK_TOTALFUEL;

	int EXTRALIFE_REWARD;

	float CUSTOMER_SPAWN_TIME;

	float WORLD_DAMAGE_SPEED_MASSIVE;
	float WORLD_DAMAGE_SPEED_LARGE;

	float PORT_DAMAGE_SPEED_MASSIVE;
	float PORT_DAMAGE_SPEED_LARGE;	

	// player
	int DEFAULT_LIVES_COUNT;
	int VERTICAL_THRUSTERS;

	float ROTATION_INCREMENT;
	float ROTATION_INCREMENT_CONFORM;
	float ROTATION_TOLERANCE;

	float MAX_TILT_ANGLE;
	float MAX_TILT_LAND_ANGLE;
	float TILT_INCREMENT;
	float TILT_INCREMENT_CONFORM;
	float TILT_TOLERANCE;

	float TILT_PUSH_FORCE;

	float MIN_VEL;
	float SLOW_DOWN;

	int MAX_FUEL;
	float FUEL_LOSS_TIME;
	float FUEL_INCREASE_TIME;
	
	int LOW_FUEL;
	int MEDIUM_FUEL;
	int NEAR_LOW_FUEL;

	float SPLASH_TIMER;
	float PORT_NUMBER_TIMER;

	float CRASH_ROTATION;

	// customers
	int CUSTOMER_MALE_MESH;
	int CUSTOMER_FEMALE_MESH;
	int CUSTOMER_PARCEL_MESH;

	int CUSTOMER_MALE_MESH_HI;
	int CUSTOMER_FEMALE_MESH_HI;
	int CUSTOMER_PARCEL_MESH_HI;

	int CUSTOMER_MALE_MESH_LOW;
	int CUSTOMER_FEMALE_MESH_LOW;
	int CUSTOMER_PARCEL_MESH_LOW;

	int CUSTOMER_MODEL_TEXTURE_START;
	int CUSTOMER_MODEL_TEXTURE_END;

	int CUSTOMER_PARCEL_TEXTURE_START;
	int CUSTOMER_PARCEL_TEXTURE_END;

	float CUSTOMER_DEPTH;
	float CUSTOMER_DROPOFF_DEPTH;

	float CUSTOMER_WALK_SPEED;
	float CUSTOMER_CLOSE_TO_TAXI;

	float LAND_TIME_ANGRY;
	float ANGRY_TIME;

	float CUSTOMER_SWEAR_BUBBLE_OFFSETX_PHONE_SD;
	float CUSTOMER_SWEAR_BUBBLE_OFFSETY_PHONE_SD;
	float CUSTOMER_SWEAR_BUBBLE_OFFSETX_PHONE_RETINA;
	float CUSTOMER_SWEAR_BUBBLE_OFFSETY_PHONE_RETINA;

	float CUSTOMER_SWEAR_BUBBLE_OFFSETX_TABLET_SD;
	float CUSTOMER_SWEAR_BUBBLE_OFFSETY_TABLET_SD;

	// scene
	float BG_QUAD_WIDTH;
	float BG_QUAD_HEIGHT;

	float BG_POS_X_DEFAULT;
	float BG_POS_Y_DEFAULT;
	float BG_POS_Z_DEFAULT;	

	bool ALLOW_DETAIL_MAPPING;
};

void RegisterCabbyFunctions( ScriptDataHolder& dataHolder );

int ScriptSetGameData( lua_State* pState );

#endif // __CABBYACCESS_H__
