
#ifndef __FRONTEND_MAINMENU_HGM_H__
#define __FRONTEND_MAINMENU_HGM_H__
// -- GENERATED BY MAYA

const int BG_SKY = 0;
const int GFX_BORDER_BOTTOM = 1;
const int GFX_LOGO = 2;
const int GFX_CADET_TAKU = 3;
const int GFX_CADET_MEI = 4;
const int GFX_CADET_EARL = 5;
const int GFX_CADET_FIO = 6;
const int GFX_CADET_MITO = 7;
const int GFX_CADET_UKI = 8;
const int BTN_GAMEMODE1 = 9;
const int BTN_GAMEMODE2 = 10;
const int BTN_GAMEMODE3 = 11;
const int BTN_MOREGAMES = 12;
const int GFX_PANEL = 13;

#endif // __FRONTEND_MAINMENU_HGM_H__
