
#ifndef __FRONTEND_LEVELSELECT_HGM_H__
#define __FRONTEND_LEVELSELECT_HGM_H__
// -- GENERATED BY MAYA

const int GFX_BG_SKY = 0;
const int GFX_BORDER_BOTTOM = 1;
const int ITEM_SLOT_OFF_1 = 2;
const int ITEM_SLOT_OFF_2 = 3;
const int ITEM_SLOT_OFF_3 = 4;
const int ITEM_SLOT_OFF_4 = 5;
const int ITEM_SLOT_ON_1 = 6;
const int ITEM_SLOT_ON_2 = 7;
const int ITEM_SLOT_ON_3 = 8;
const int ITEM_SLOT_ON_4 = 9;
const int GFX_BG_PAGINATION = 10;
const int GFX_BG_LAYOUT = 11;

#endif // __FRONTEND_LEVELSELECT_HGM_H__
