

#ifndef __HUD_HUI_H__
#define __HUD_HUI_H__

// -- GENERATED BY MAYA

const int HUI_BUTTON_PAUSE = 1000;
const int HUI_TEXT_PAUSE = 1001;
const int HUI_TEXT_COUNTDOWN = 1002;
const int HUI_LABEL_SCORE = 1003;
const int HUI_LABEL_TIME = 1004;

#endif // __HUD_HUI_H__
