

#ifndef __ICONS_TABLET_SD_HUI_H__
#define __ICONS_TABLET_SD_HUI_H__

// -- GENERATED BY MAYA

const int HUI_ICON_TARGET_1 = 1000;
const int HUI_ICON_TARGET_2 = 1001;
const int HUI_ICON_TARGET_3 = 1002;
const int HUI_ICON_TARGET_4 = 1003;
const int HUI_ICON_TARGET_5 = 1004;
const int HUI_ICON_TARGET_6 = 1005;
const int HUI_ICON_TARGET_7 = 1006;
const int HUI_ICON_TARGET_8 = 1007;
const int HUI_ICON_TARGET_9 = 1008;
const int HUI_ICON_TARGET_10 = 1009;

#endif // __ICONS_TABLET_SD_HUI_H__
