
#ifndef __ICONS_TABLET_SD_HGM_H__
#define __ICONS_TABLET_SD_HGM_H__
// -- GENERATED BY MAYA

const int ICON_TARGET_1 = 0;
const int ICON_TARGET_2 = 1;
const int ICON_TARGET_3 = 2;
const int ICON_TARGET_4 = 3;
const int ICON_TARGET_5 = 4;
const int ICON_TARGET_6 = 5;
const int ICON_TARGET_7 = 6;
const int ICON_TARGET_8 = 7;
const int ICON_TARGET_9 = 8;
const int ICON_TARGET_10 = 9;

#endif // __ICONS_TABLET_SD_HGM_H__
