
#ifndef __INGAME_LEVELSTART_HGM_H__
#define __INGAME_LEVELSTART_HGM_H__
// -- GENERATED BY MAYA

const int GFX_BG_SKY = 0;
const int GFX_BORDER_BOTTOM = 1;
const int BG_LEVELNAME = 2;
const int BG_BGM_SELECT = 3;
const int BG_TRACKNAME = 4;

#endif // __INGAME_LEVELSTART_HGM_H__
