
#ifndef __INGAME_PAUSED_HGM_H__
#define __INGAME_PAUSED_HGM_H__
// -- GENERATED BY MAYA

const int GFX_BG_DIMMER = 0;
const int GFX_BG_BORDER_BOTTOM = 1;
const int GFX_BG_PANEL = 2;
const int GFX_CADET_TAKU = 3;
const int GFX_CADET_MEI = 4;
const int GFX_CADET_EARL = 5;
const int GFX_CADET_FIO = 6;
const int GFX_CADET_MITO = 7;
const int GFX_CADET_UKI = 8;

#endif // __INGAME_PAUSED_HGM_H__
