#ifndef __FRONTEND_HUI_H__
#define __FRONTEND_HUI_H__

// -- GENERATED BY MAYA

const int BG_POS = -9999;
const int LOSTDATA_POS = -9999;
const int BAR_POS_TOP = 11;
const int BTN_BACK = 99;
const int BAR_TITLE_BG = 12;
const int BAR_POS_BOTTOM = 20;
const int CREDITS_AREA = 33;
const int LABEL_PRISONER84_TITLE = 0;
const int LABEL_START = 1;
const int LABEL_ABOUT = 2;
const int LABEL_OPTIONS = 3;
const int LABEL_ACHIEVEMENTS_GLYPH = 100;
const int LABEL_RATE = 101;
const int LABEL_MOREGAMES = 102;
const int LABEL_CONTINUE = 4;
const int LABEL_NEWGAME = 5;
const int LABEL_NEWGAME_NOSAVE = 6;
const int LABEL_PASTRANKING = 7;
const int LABEL_YES = 8;
const int LABEL_NO = 9;
const int LABEL_PROMPT = 10;
const int LABEL_BACK = 13;
const int LABEL_TITLE = 14;
const int LOGO_POS = 15;
const int LABEL_HEAD1 = 16;
const int LABEL_NAME1 = 17;
const int LABEL_HEAD2 = 18;
const int LABEL_NAME2 = 19;
const int LABEL_COPYRIGHT = 21;
const int LABEL_TESTERS_TITLE = 22;
const int LABEL_TESTER1 = 23;
const int LABEL_TESTER2 = 24;
const int LABEL_TESTER3 = 25;
const int LABEL_TESTER4 = 26;
const int LABEL_TESTER5 = 27;
const int LABEL_TESTER6 = 28;
const int LABEL_TESTER7 = 29;
const int LABEL_TESTER8 = 30;
const int LABEL_TESTER9 = 31;
const int LABEL_TESTER10 = 32;

#endif // __FRONTEND_HUI_H__
