
#ifndef __FRONTEND_HGM_H__
#define __FRONTEND_HGM_H__
// -- GENERATED BY MAYA

const int BG = 0;
const int BLOOD = 1;
const int TEXT_LOSTDATA = 2;
const int LOGO = 3;
const int BTN_EXIT = 4;
const int TITLE_BG = 5;
const int DIM_BOTTOM = 6;
const int DIM_TOP = 7;

#endif // __FRONTEND_HGM_H__
