
#ifndef __GAMEOVER_HGM_H__
#define __GAMEOVER_HGM_H__
// -- GENERATED BY MAYA

const int GAMEOVER_BG = 0;
const int GAMEOVER_DIM_TOP = 1;
const int GAMEOVER_PANEL1 = 2;
const int GAMEOVER_PANEL2 = 3;
const int GAMEOVER_PANEL3 = 4;
const int GAMEOVER_BLOOD = 5;
const int GAMEOVER_DOCUMENTS = 6;
const int GAMEOVER_TOKENS = 7;
const int GAMEOVER_HEADS = 8;

#endif // __GAMEOVER_HGM_H__
