

#ifndef __INVENTORY_HUI_H__
#define __INVENTORY_HUI_H__

// -- GENERATED BY MAYA

const int HUI_BTN_EXIT = 3;
const int BTN_TOGGLE_INVENTORY = 4;
const int BTN_TOGGLE_COLLECTABLES = 5;
const int BTN_SLOT1 = 8;
const int BTN_SLOT2 = 9;
const int BTN_SLOT3 = 10;
const int BTN_SLOT4 = 11;
const int BTN_SLOT5 = 12;
const int BTN_SLOT6 = 13;
const int BTN_SLOT7 = 14;
const int BTN_SLOT8 = 15;
const int BTN_SLOT9 = 16;
const int BTN_SLOT10 = 17;
const int BTN_SLOT11 = 18;
const int BTN_SLOT12 = 19;
const int BTN_SLOT13 = 20;
const int BTN_SLOT14 = 21;
const int BTN_SLOT15 = 22;
const int BTN_SLOT16 = 23;
const int BTN_SLOT17 = 24;
const int BTN_SLOT18 = 25;
const int BG_POS = 26;
const int BG_TOPBAR_POS = 27;
const int BTN_SLOT1_OUTLINE = 28;
const int BTN_SLOT2_OUTLINE = 29;
const int BTN_SLOT3_OUTLINE = 30;
const int BTN_SLOT4_OUTLINE = 31;
const int BTN_SLOT5_OUTLINE = 32;
const int BTN_SLOT6_OUTLINE = 33;
const int BTN_SLOT7_OUTLINE = 34;
const int BTN_SLOT8_OUTLINE = 35;
const int BTN_SLOT9_OUTLINE = 36;
const int BTN_SLOT10_OUTLINE = 37;
const int BTN_SLOT11_OUTLINE = 38;
const int BTN_SLOT12_OUTLINE = 39;
const int BTN_SLOT13_OUTLINE = 40;
const int BTN_SLOT14_OUTLINE = 41;
const int BTN_SLOT15_OUTLINE = 42;
const int BTN_SLOT16_OUTLINE = 43;
const int BTN_SLOT17_OUTLINE = 44;
const int BTN_SLOT18_OUTLINE = 45;
const int LABEL_INVENTORY = 0;
const int LABEL_COLLECTABLES = 1;
const int LABEL_EXIT = 2;
const int LABEL_DESCRIPTION_LINE1 = 6;
const int LABEL_DESCRIPTION_LINE2 = 7;

#endif // __INVENTORY_HUI_H__
