
#ifndef __OPTIONSGAME_HGM_H__
#define __OPTIONSGAME_HGM_H__
// -- GENERATED BY MAYA

const int BTN_QUIT = 0;
const int BTN_RESUME = 1;
const int TITLE_BG = 2;
const int PANEL1 = 3;
const int BTN_LERP_OFF_INACTIVE = 4;
const int BTN_LERP_OFF_ACTIVE = 5;
const int BTN_LERP_ON_INACTIVE = 6;
const int BTN_LERP_ON_ACTIVE = 7;
const int LABEL_OFF = 8;
const int LABEL_MEDIUM = 9;
const int LABEL_HIGH = 10;
const int SLIDER_BG = 11;
const int SCRUBBER_INACTIVE = 12;
const int SCRUBBER_ACTIVE = 13;
const int BTN_FPSMODE_OFF_INACTIVE = 14;
const int BTN_FPSMODE_OFF_ACTIVE = 15;
const int BTN_FPSMODE_ON_INACTIVE = 16;
const int BTN_FPSMODE_ON_ACTIVE = 17;
const int LOCK_FPSMODE = 18;

#endif // __OPTIONSGAME_HGM_H__
